name: Check compilation

on:
  push:

jobs:
  check:  
    runs-on: ubuntu-latest  
    steps: 
    - name: Install libudev
      run: sudo apt-get install libudev-dev

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Check that code can compile
      run: cargo check
